stages:
  - build
  - test

default:
  image: "mshindle/golang-extra:latest"

compile:
  stage: "build"
  script:
    - go mod download
    - go build main.go

test-all:
  stage: "test"
  script:
    - go test ./...
