stages:
  - test
  - build

default:
  image: "mshindle/golang-extra:latest"

test-all:
  stage: "test"
  script:
    - echo "running tests..."
    - go mod tidy
    - go test -v ./...

compile:
  stage: "build"
  script:
    - echo "building application..."
    - CGO_ENABLED=1 go build -o tidbits main.go
  artifacts:
    paths:
      - tidbits # Store the built executable as an artifact
    expire_in: 1 week


