package toy

import (
	"math/rand"

	"github.com/apex/log"
)

func nextPowerOf2(n uint) uint {
	if n > 0 && (n&(n-1)) == 0 {
		return n
	}

	var count uint
	for k := n; k != 0; k >>= 1 {
		log.WithFields(log.Fields{"k": k, "count": count}).Debug("iterating to next power of 2")
		count += 1
	}
	return 1 << count
}

func flip() bool {
	return rand.Int()%2 == 0
}

// RandRange takes a given function flip() which simulates a coin-flip and
// returns 1 50% of the time and 0 50% of the time, write a function
// random(n) that generates a random number between 0 & n-1 with
// a normal distribution pattern
// PseudoCode of the logic...
// Let m = 2^k >= n where k is as small as possible.
// do
//   Let r = random number in 0 .. m-1 generated by k coin flips
// while r >= n
// return r
func RandRange(n uint) uint {
	var r = ^uint(0)

	// figure out min # of bits to describe numbers
	var minBits uint
	m := nextPowerOf2(n)
	log.WithField("nextPower2", m).Info("next power number calculated")
	for p := m; p != 0; p >>= 1 {
		minBits += 1
	}
	log.WithField("minBits", minBits).Info("number of bits to set")

	// calculate
	for r >= n {
		var generated, i uint
		for i = 0; i < minBits-1; i++ {
			if flip() {
				generated |= 1 << i
				log.WithField("generated", generated).Debug("flip true")

			} else {
				log.WithField("generated", generated).Debug("flip false")
			}
		}
		r = generated
		log.WithField("r", r).Info("number generated")
	}

	return r
}
